runtime: nodejs20  # Use the appropriate Node.js version
instance_class: B2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

env_variables:
  DB_USER: rifal
  DB_PASSWORD: password123
  DB_NAME: advokataDB
  CLOUD_SQL_CONNECTION_NAME: artful-mystery-441112-u2:asia-southeast2:db-advokata
  GCS_BUCKET_NAME : advokata-1933-bucket
